__author__ = 'sud'
from django.conf.urls import patterns, url
from fringe_x import views

urlpatterns=patterns('',
                     url(r'^/$',views.fringecircle_index),
                     url(r'^/fringe_x/$',views.fringex_index),
                     url(r'^/post_ad/$',views.post_ad),
                     url(r'^/post_ad/(?P<subcategory_name>.+)/$',views.post_ad),
                     url(r'^/product_list/(?P<subcategory_name>.+)/$',views.product_list),
                     url(r'^/product_list/$',views.product_list),
                     url(r'^/product_grid/$',views.product_grid),
                     url(r'^/product_grid/(?P<subcategory_name>.+)/$',views.product_grid),
                     url(r'^/fetch_locality_names/(?P<city_name>.+)/$',views.fetch_locality),
                     url(r'^/fetch_city_names/(?P<state_name>.+)/$',views.fetch_city),
                     url(r'^/fetch_state_names/$',views.fetch_all_states),
                     url(r'^/location_selection/(?P<location_param>.+)/$',views.location_selection),
                     url(r'/fetch_subcategory_names/(?P<prime_cat_name>.+)/$',views.fetch_subcategory_names),
                     url(r'^/fetch_prime_filters/(?P<prime_cat_name>.+)/$',views.fetch_prime_filters),
                     url(r'^/fetch_sub_filters/(?P<sub_cat_name>.+)/$',views.fetch_sub_filters),
                     url(r'^/fetch_prime_filter_masters/(?P<prime_filter_name>.+)/$',views.fetch_prime_filter_masters),
                     url(r'^/fetch_first_subfilter_masters/(?P<subcategory_name>.+)/$',views.fetch_first_sub_filter_masters),
                     url(r'^/fetch_sub_filter_masters/(?P<sub_filter_name>.+)/$',views.fetch_sub_filter_masters),
                     url(r'^/ad/(?P<ad_id>.+)/$',views.individual_ad),
                     url(r'^/grid/$',views.product_grid),
                     url(r'^/acceptdata/(?P<ad_parameters>.+)/$',views.get_filter_ads),
                     url(r'^/article_data/$',views.post_data),
                     url(r'^/article_form/$',views.post_form),
                     url(r'^/login/$',views.login),
                     url(r'^/logout/$',views.logout),
                     url(r'^/signup/$',views.signup),
                     url(r'^/register_user/(?P<registration_token>.+)/$',views.register_user_page),
                     url(r'^/register_corporate_email/$',views.send_registration_email),
                     url(r'^/register_user_db/(?P<registration_token>.+)/$',views.register_user),
                     )